language: java

jdk:
  - oraclejdk8
  - openjdk8

sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=groovylabs/lyre
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64

dist: trusty

os:
  - linux

branches:
  only:
  - master
  - develop

addons:
  sonarcloud:
    organization: "groovylabs"
    token:
      secure: 958c4e2aeadff503e43c1a38a80efe7ec8d1ee88
    branches:
      - master
      - develop

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - export TAG=`if [[ $TRAVIS_BRANCH == "develop" ]]; then echo "build-"$TRAVIS_BUILD_NUMBER; fi`
  - export REPO=groovylabs/lyre
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then
      docker build -t $REPO:$TAG -f Dockerfile .;
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      docker tag $REPO $REPO:$TAG;
      docker push $REPO:$TAG;
    fi;
