language: java

jdk:
  - oraclejdk8
  - openjdk8

dist: trusty

os:
  - linux

branches:
  only:
  - master
  - develop

addons:
  sonarcloud:
    organization: "groovylabs"
    token:
      secure: 958c4e2aeadff503e43c1a38a80efe7ec8d1ee88

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

